### ISSUE TITLE
依然登录验证失败

### ISSUE THREAD

**Issue by Enderman-Teleporting** [simple-robot/simpler-robot#545]
### 版本号

v2.5.0

### 附加版本

协议Android pad

### 问题描述

无法登陆

### 复现方式

完成登录验证后报错

### 相关日志

```Text
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at love.forte.common.ioc.MethodDependPass.invoke(DependPass.kt:76)
        at love.forte.common.ioc.DependCenter.init(DependCenter.kt:108)
        at love.forte.simbot.core.SimbotApp.initDependCenter(SimbotApp.kt:436)
        at love.forte.simbot.core.SimbotApp.run$core(SimbotApp.kt:281)
        at love.forte.simbot.core.SimbotApp$Run.run(SimbotApp.kt:510)
        at love.forte.simbot.core.SimbotApp$Run.run$default(SimbotApp.kt:474)
        at love.forte.simbot.core.SimbotApp$Run.run(SimbotApp.kt)
        at love.forte.simbot.core.SimbotApp.run(SimbotApp.kt)
        at love.simbot.example.SimbotExampleApplication.main(SimbotExampleApplication.java:21)
        ... 8 more
Caused by: java.lang.IllegalStateException: Can't overwrite cause with a null
        at java.base/java.lang.Throwable.initCause(Throwable.java:463)
        at love.forte.simbot.component.mirai.configuration.MiraiBotVerifier.verity(MiraiBotVerifier.kt:115)
        at love.forte.simbot.component.mirai.configuration.MiraiBotManager.registerBot(MiraiBotManager.kt:103)
        at love.forte.simbot.core.configuration.CoreBotRegistrar.registerBots(CoreBotRegistrar.kt:65)
        ... 21 more
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(766979001), code=45, title=禁止登录, message=您好，您当前使用的版本过低，前往QQ官网im.qq.com下载新版QQ。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:309)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by ForteScarlet** [comment]
参考[此问题](https://github.com/orgs/simple-robot/discussions/34) ，协议调整为了PAD相关之后清理 `cache` 文件和可能存在的 `device.json` 文件后再尝试。
